// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp-pQKofFo4Y0OLLw5JgT41F0tbpoThnU',
    appId: '1:141037340980:web:ae9bf7584486bb9d4e3d61',
    messagingSenderId: '141037340980',
    projectId: 'mobiluygulama-dcc74',
    authDomain: 'mobiluygulama-dcc74.firebaseapp.com',
    storageBucket: 'mobiluygulama-dcc74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSCYM4V0qK0ubGkCJ5kxBtQKVoBFJqFU',
    appId: '1:141037340980:android:f669d6e2ba43f2454e3d61',
    messagingSenderId: '141037340980',
    projectId: 'mobiluygulama-dcc74',
    storageBucket: 'mobiluygulama-dcc74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAUADXjVmb9YWxtSkDYmPdJZHIGPHchVs',
    appId: '1:141037340980:ios:9518b84bfa12c7ad4e3d61',
    messagingSenderId: '141037340980',
    projectId: 'mobiluygulama-dcc74',
    storageBucket: 'mobiluygulama-dcc74.firebasestorage.app',
    iosBundleId: 'com.example.denemeProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAUADXjVmb9YWxtSkDYmPdJZHIGPHchVs',
    appId: '1:141037340980:ios:9518b84bfa12c7ad4e3d61',
    messagingSenderId: '141037340980',
    projectId: 'mobiluygulama-dcc74',
    storageBucket: 'mobiluygulama-dcc74.firebasestorage.app',
    iosBundleId: 'com.example.denemeProjesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp-pQKofFo4Y0OLLw5JgT41F0tbpoThnU',
    appId: '1:141037340980:web:3c3f9dab1d618c0a4e3d61',
    messagingSenderId: '141037340980',
    projectId: 'mobiluygulama-dcc74',
    authDomain: 'mobiluygulama-dcc74.firebaseapp.com',
    storageBucket: 'mobiluygulama-dcc74.firebasestorage.app',
  );
}
